# Generated by Django 5.2 on 2025-04-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('quantityShipped', models.IntegerField()),
                ('expectedArrival', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('item', models.ForeignKey(db_column='itemID', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('store', models.ForeignKey(db_column='storeID', on_delete=django.db.models.deletion.CASCADE, to='inventory.store')),
            ],
        ),
    ]
